# Generated by Django 4.1.5 on 2023-01-09 16:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('pays', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TailleVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('date_de_creation', models.DateField()),
                ('taille_de_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.taillevehicule')),
                ('type_de_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_journalier', models.IntegerField()),
                ('taille_de_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.taillevehicule')),
                ('type_de_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_location', models.DateField()),
                ('date_de_retour', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.customer')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehicule')),
            ],
        ),
    ]
