# Generated by Django 4.1.5 on 2023-01-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='upload_image/', verbose_name='Photo de profil'),
        ),
    ]
