# Generated by Django 4.1.5 on 2023-01-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='famille',
            old_name='name',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='famille',
            name='numero',
        ),
    ]
