# Generated by Django 4.1.5 on 2023-01-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal2', '0002_rename_name_famille_nom_remove_famille_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal2.famille'),
        ),
    ]
