# Generated by Django 4.1.5 on 2023-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal2', '0003_alter_animal_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='family',
            field=models.IntegerField(),
        ),
    ]
